temperature_base: 10.0
high_temp_threshold: 33.0
low_temp_threshold: 20.0
base_feature_names:
  - latitude
  - altitude
  - transplanting_doy

window_feature_families:
  - tmean
  # - paccum
  # - rmean
  # - hdd
  # - cdd
windows:
  - [tran0_10, 0, 10]
  - [tran0_20, 0, 20]
  - [tran0_30, 0, 30]
  - [tran0_60, 0, 60]
  - [tran0_90, 0, 90]
  - [tran0_120, 0, 120]
  - [tran90_120, 90, 120]
explicit_feature_names: []
feature_selection:
  vif_threshold: 10.0
  top_k_scatter: 2
